app:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      schema-registry-url: ${SCHEMA_REGISTRY_URL}
      group-id: important-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      auto-commit: false
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      schema-registry-url: ${SCHEMA_REGISTRY_URL}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer